
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="relative antialiased px-[16px] md:px-[32px] lg:px-[60px] bg-Neutral100"
      >
        <Header />
        {children}
        <Footer />
        <div id="mobile-nav"></div>
      </body>
    </html>
  );
}
