export const projects = [
    {
        img: '/character.png',
        name: 'Character Counter',
        description: "A sleek utility that analyzes your text in real-time, tracking characters, words, sentences, and reading time. Features include space exclusion, custom character limits, and letter density insights. Enhanced with a theme toggle (light/dark mode) and smooth animations. Built with React and Tailwind CSS.",
        link: "https://dhb-lee5-igaf.vercel.app/",
        codelink: "https://github.com/DHBLee/DHBLee5/tree/DHBLee/Fronend-Mentor/Counter",
        techstack: ["React", "TailwindCSS", "Vite"],
    },
    {
        img: '/countries.png',
        name: 'Countries',
        description: 'A country information website featuring details about selected nations worldwide. Includes dark/light theme toggle, region filtering, and search functionality. Built with HTML, JavaScript, and SCSS, using JSON data for country information.',
        link: 'https://dhb-lee3-omh8.vercel.app/index.html',
        codelink: 'https://github.com/DHBLee/DHBLee3/tree/DHBLee/Fronend-Mentor/Countries',
        techstack: ["HTML", "SCSS", "JavaScript"],
    },
    {
        img: '/ecommerce.png',
        name: 'One-Page Ecommerce Design',
        description: 'A single-page e-commerce demo with interactive product display, quantity adjuster, and cart modal that calculates totals. Built with HTML, CSS, and JavaScript.',
        link: 'https://dhb-lee2-gcm1.vercel.app/',
        codelink: 'https://github.com/DHBLee/DHBLee2/tree/DHBLee/Fronend-Mentor/Ecommerce',
        techstack: ["HTML", "CSS", "JavaScript"],
    },
    {
        img: '/job.png',
        name: 'Job Application',
        description: 'A job listing platform with filtering functionality. Built with HTML, CSS, and JavaScript.',
        link: 'https://dhb-lee2-8hsn.vercel.app/',
        codelink: 'https://github.com/DHBLee/DHBLee2/tree/DHBLee/Fronend-Mentor/Job',
        techstack: ["HTML", "CSS", "JavaScript"],
    },
    {
        img: '/markdown.png',
        name: 'Markdown Editor',
        description: 'A dynamic tool that automatically formats plain text into Markdown by analyzing line patterns. Features theme switching, smooth animations, and intelligent styling for headings, lists, and quotes. Built with React and Tailwind CSS.',
        link: 'https://dhb-lee6-h73a.vercel.app/',
        codelink: 'https://github.com/DHBLee/DHBLee6/tree/DHBLee/Fronend-Mentor/Markdown/vite-markdown',
        techstack: ["React", "TailwindCSS", "Vite"],
    },
    {
        img: '/quiz.png',
        name: 'Quiz App',
        description: 'A dynamic trivia game with multiple topics, timed questions, and score tracking. Features a theme toggle (light/dark mode) and smooth animations for an engaging experience. Built with React and Tailwind CSS.',
        link: 'https://dhb-lee6-xdna.vercel.app/',
        codelink: 'https://github.com/DHBLee/DHBLee6/tree/DHBLee/Fronend-Mentor/Quiz/quiz-vite',
        techstack: ["React", "TailwindCSS", "Vite"],
    },
    {
        img: '/rps.png',
        name: 'Rock Paper Scissors',
        description: 'An interactive Rock Paper Scissors game featuring real-time score tracking, a response timer, and a rules modal. Built with HTML, JavaScript, and SCSS for dynamic gameplay and styling.',
        link: 'https://dhb-lee3-pj4v.vercel.app/',
        codelink: 'https://github.com/DHBLee/DHBLee3/tree/DHBLee/Fronend-Mentor/RPS-Game',
        techstack: ["HTML", "SCSS", "JavaScript"],
    },
    {
        img: '/space.png',
        name: 'Space Website',
        description: 'A multi-page space exploration website featuring interactive hover effects, smooth animations, and dynamic page transitions. Built with HTML, JavaScript, and SCSS for a seamless browsing experience',
        link: 'https://dhb-lee5.vercel.app/',
        codelink: 'https://github.com/DHBLee/DHBLee5/tree/DHBLee/Fronend-Mentor/Space',
        techstack: ["HTML", "SCSS", "JavaScript"],
    },
    {
        img: '/tic-tac-toe.png',
        name: 'Tic Tac Toe',
        description: 'A responsive and interactive Tic Tac Toe game with Player vs. Player (PvP) and Player vs. Computer (PvC) modes. Features score tracking, smooth animations, and quick game reset options. Built with React and Tailwind CSS for a clean, modern UI.',
        link: 'https://dhb-lee6-1424.vercel.app/',
        codelink: 'https://github.com/DHBLee/DHBLee6/tree/DHBLee/Fronend-Mentor/Tictactoe/vite-tictactoe',
        techstack: ["React", "TailwindCSS", "Vite"],
    },
    {
        img: '/todo.png',
        name: 'Todo List',
        description: 'An interactive to-do list application with task management features including add/remove items, completion status toggle, and filtering (all/active/completed). Includes drag-and-drop reordering, hover transitions, and light/dark theme toggle. Built with HTML, CSS, and JavaScript.',
        link: 'https://dhb-lee2-rtdh.vercel.app/#',
        codelink: 'https://github.com/DHBLee/DHBLee2/tree/main/todo-app-main',
        techstack: ["HTML", "CSS", "JavaScript"],
    },
]